/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jurado_project;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ken
 */
public class DogeCRUDScreen extends javax.swing.JFrame {

    /**
     * Creates new form DogeCRUDScreen
     */
    DBHelper1 dbh = new DBHelper1();
    public DogeCRUDScreen(){
        initComponents();
        try {
            dbh.connectDB();
        } catch (Exception ex) {
            Logger.getLogger(DogeCRUDScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDisplay = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisplayRecords = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txfldId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txfldFirstname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txfldLastname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txfldMobile = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txfldBrand = new javax.swing.JTextField();
        txfldFlavor = new javax.swing.JTextField();
        txfldTypeofpackage = new javax.swing.JTextField();
        txfldKilogram = new javax.swing.JTextField();
        txfldDelivery = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txflddogfood_id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txfldType_id = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txfldDelivery_id = new javax.swing.JTextField();
        txfldpayment_id = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txfldPayment = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txfldPrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 245, 220));

        btnDisplay.setBackground(new java.awt.Color(255, 153, 0));
        btnDisplay.setText("Display All");
        btnDisplay.setName("btnDisplay"); // NOI18N
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        tblDisplayRecords.setBackground(new java.awt.Color(245, 245, 220));
        tblDisplayRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "firstname", "lastname", "mobile_num", "brand", "flavor", "typeofpackage", "kilogram", "price", "delivery"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDisplayRecords.setName("tblDisplayRecords"); // NOI18N
        jScrollPane1.setViewportView(tblDisplayRecords);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(148, 107, 69));
        jLabel1.setText("Doge read, update, delete");

        jLabel2.setText("Customer ID");

        txfldId.setName("txfldId"); // NOI18N

        jLabel3.setText("First Name");

        txfldFirstname.setToolTipText("");
        txfldFirstname.setName("txfldFirstname"); // NOI18N
        txfldFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfldFirstnameActionPerformed(evt);
            }
        });

        jLabel4.setText("Last Name");
        jLabel4.setToolTipText("");

        txfldLastname.setName("txfldLastname"); // NOI18N

        jLabel5.setText("Mobile Number");

        btnSearch.setBackground(new java.awt.Color(255, 153, 0));
        btnSearch.setText("Search");
        btnSearch.setName("btnSearch"); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 153, 0));
        btnUpdate.setText("Update");
        btnUpdate.setName("btnUpdate"); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 153, 0));
        btnDelete.setText("Delete");
        btnDelete.setName("btnDelete"); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 153, 0));
        btnClear.setText("Clear");
        btnClear.setToolTipText("");
        btnClear.setName("btnClear"); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 153, 0));
        btnExit.setText("Exit");
        btnExit.setName("btnExit"); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        txfldBrand.setName("txfldBrand"); // NOI18N
        txfldBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfldBrandActionPerformed(evt);
            }
        });

        txfldFlavor.setName("txfldFlavor"); // NOI18N

        txfldTypeofpackage.setName("txfldTypeofpackage"); // NOI18N

        txfldKilogram.setName("txfldKilogram"); // NOI18N

        txfldDelivery.setName("txfldDelivery"); // NOI18N

        jLabel6.setText("Brand");

        jLabel7.setText("Flavor");

        jLabel8.setText("Type of Package");

        jLabel9.setText("Kilogram");

        jLabel10.setText("Delivery");

        txflddogfood_id.setName("txflddogfood_id"); // NOI18N

        jLabel11.setText("Dog Food ID");

        jLabel12.setText("Type ID");

        txfldType_id.setToolTipText("");
        txfldType_id.setName("txfldType_id"); // NOI18N
        txfldType_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfldType_idActionPerformed(evt);
            }
        });

        jLabel13.setText("Delivery ID");

        txfldDelivery_id.setToolTipText("");
        txfldDelivery_id.setName("txfldDelivery_id"); // NOI18N

        txfldpayment_id.setToolTipText("");
        txfldpayment_id.setName("txfldpayment_id"); // NOI18N
        txfldpayment_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfldpayment_idActionPerformed(evt);
            }
        });

        jLabel14.setText("Payment ID");

        jLabel15.setText("Payment");

        txfldPayment.setName("txfldPayment"); // NOI18N

        jLabel16.setText("Price");

        txfldPrice.setName("txfldPrice"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(btnDisplay))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txfldTypeofpackage))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)))
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txflddogfood_id, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfldFlavor, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfldBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfldType_id, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(28, 28, 28)))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfldFirstname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfldLastname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfldMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfldId, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfldKilogram)
                            .addComponent(txfldDelivery)
                            .addComponent(txfldDelivery_id)
                            .addComponent(txfldpayment_id)
                            .addComponent(txfldPayment)
                            .addComponent(txfldPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(330, 330, 330))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txfldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txfldFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txfldLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txfldMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSearch)
                                .addGap(5, 5, 5)
                                .addComponent(btnUpdate)
                                .addGap(6, 6, 6)
                                .addComponent(btnDelete)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txflddogfood_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txfldBrand)
                                    .addComponent(jLabel6))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txfldFlavor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txfldType_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfldTypeofpackage, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(btnExit))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txfldKilogram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txfldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16))
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel13))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(txfldDelivery_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txfldDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfldpayment_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisplay)
                    .addComponent(jLabel15)
                    .addComponent(txfldPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        // TODO add your handling code here:
        try{
        ResultSet rs = dbh.dogeDisplayRecords();
        
        while(tblDisplayRecords.getRowCount() > 0){
            ((DefaultTableModel) tblDisplayRecords.getModel()).removeRow(0);
        }
        int columns = rs.getMetaData().getColumnCount();
        while(rs.next()){
            Object[] row = new Object[columns];
            for (int i = 1; i <= columns; i++){
                row[i - 1] = rs.getObject(i);
            }
            ((DefaultTableModel)tblDisplayRecords.getModel()).insertRow(rs.getRow()-1,row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DogeCRUDScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void txfldFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfldFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfldFirstnameActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            // TODO add your handling code here:
            int cust_id = Integer.parseInt(txfldId.getText());
            ResultSet rs = dbh.displayCustomerID(cust_id);
            while(rs.next()){
                txfldFirstname.setText(rs.getString(2));
                txfldLastname.setText(rs.getString(3));
                txfldMobile.setText(rs.getString(4));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DogeCRUDScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            // TODO add your handling code here:
            int dogfood_id = Integer.parseInt(txflddogfood_id.getText());
            ResultSet rs = dbh.displayDogfoodID(dogfood_id);
            while(rs.next()){
                txfldBrand.setText(rs.getString(2));
                txfldFlavor.setText(rs.getString(3));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DogeCRUDScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            // TODO add your handling code here:
            int type_id = Integer.parseInt(txfldType_id.getText());
            ResultSet rs = dbh.displayTypeID(type_id);
            while(rs.next()){
                txfldTypeofpackage.setText(rs.getString(3));
                txfldKilogram.setText(rs.getString(4));
                txfldPrice.setText(rs.getString(5));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DogeCRUDScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            // TODO add your handling code here:
            int delivery_id = Integer.parseInt(txfldDelivery_id.getText());
            ResultSet rs = dbh.displayDeliveryID(delivery_id);
            while(rs.next()){
                txfldDelivery.setText(rs.getString(3));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DogeCRUDScreen.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            // TODO add your handling code here:
            int payment_id = Integer.parseInt(txfldpayment_id.getText());
            ResultSet rs = dbh.displayPaymentID(payment_id);
            while(rs.next()){
                txfldPayment.setText(rs.getString(2));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DogeCRUDScreen.class.getName()).log(Level.SEVERE, null, ex);
        }                
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int cust_id = Integer.parseInt(txfldId.getText());
        String firstname = txfldFirstname.getText();
        String lastname = txfldLastname.getText();
        String mobile_num = txfldMobile.getText();
        
        int dogfood_id = Integer.parseInt(txflddogfood_id.getText());
        String brand = txfldBrand.getText();
        String flavor = txfldFlavor.getText();
        
        int type_id = Integer.parseInt(txflddogfood_id.getText());
        String typeofpackage = txfldTypeofpackage.getText();
        int kilogram = Integer.parseInt(txfldKilogram.getText());
        int price = Integer.parseInt(txfldPrice.getText());
        
        int delivery_id = Integer.parseInt(txfldDelivery_id.getText());
        String deliveryboolean = txfldDelivery.getText();
        
        int payment_id = Integer.parseInt(txfldpayment_id.getText());
        int payment = Integer.parseInt(txfldPayment.getText());

        boolean updcus = dbh.updateRecordCustomer(cust_id, firstname, lastname, mobile_num);
        boolean upddog = dbh.updateRecordDogfood(dogfood_id, brand, flavor);
        boolean updtype = dbh.updateRecordType(type_id, typeofpackage, kilogram, price);
        boolean upddel = dbh.updateRecordDelivery(delivery_id, deliveryboolean);
        boolean updpay = dbh.updateRecordPayment(payment_id, payment);
        
        if (updcus){
            System.out.println("Record updated");
        }
        else if (upddog){
            System.out.println("Record updated");
        }
        else if(updtype){
            System.out.println("Record updated");
        }
        else if(upddel){
            System.out.println("Record updated");
        }
        else if(updpay){
            System.out.println("Record updated");
        }
        else{    
            System.out.println("Reocrd not updated");
        }
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int cust_id = Integer.parseInt(txfldId.getText());
        int rescust = JOptionPane.showConfirmDialog(this, "Do you want to delete this record?", "Delete Record", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (rescust == JOptionPane.YES_OPTION){
            boolean del = dbh.deleteRecordCustomer(cust_id);

            if (del)
            JOptionPane.showMessageDialog(this, "Record deleted");
            else
            JOptionPane.showMessageDialog(this, "Reocrd not deleted");
        }
        
        int dogfood_id = Integer.parseInt(txflddogfood_id.getText());
        int resdog = JOptionPane.showConfirmDialog(this, "Do you want to delete this record?", "Delete Record", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
            if (resdog == JOptionPane.YES_OPTION){
            boolean del = dbh.deleteRecordDogfood(dogfood_id);

            if (del)
            JOptionPane.showMessageDialog(this, "Record deleted");
            else
            JOptionPane.showMessageDialog(this, "Reocrd not deleted");
        }
        
        int type_id = Integer.parseInt(txfldType_id.getText());
        int restype = JOptionPane.showConfirmDialog(this, "Do you want to delete this record?", "Delete Record", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (restype == JOptionPane.YES_OPTION){
            boolean del = dbh.deleteRecordType(type_id);

            if (del)
            JOptionPane.showMessageDialog(this, "Record deleted");
            else
            JOptionPane.showMessageDialog(this, "Reocrd not deleted");
        }

        int delivery_id = Integer.parseInt(txfldDelivery_id.getText());
        int resdel = JOptionPane.showConfirmDialog(this, "Do you want to delete this record?", "Delete Record", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (resdel == JOptionPane.YES_OPTION){
            boolean del = dbh.deleteRecordDelivery(delivery_id);

            if (del)
            JOptionPane.showMessageDialog(this, "Record deleted");
            else
            JOptionPane.showMessageDialog(this, "Reocrd not deleted");
        }

        int payment_id = Integer.parseInt(txfldpayment_id.getText());
        int respay = JOptionPane.showConfirmDialog(this, "Do you want to delete this record?", "Delete Record", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (respay == JOptionPane.YES_OPTION){
            boolean del = dbh.deleteRecordPayment(payment_id);

            if (del)
            JOptionPane.showMessageDialog(this, "Record deleted");
            else
            JOptionPane.showMessageDialog(this, "Reocrd not deleted");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txfldId.setText("");
        txfldFirstname.setText("");
        txfldLastname.setText("");
        txfldMobile.setText("");
        txflddogfood_id.setText("");
        txfldBrand.setText("");
        txfldFlavor.setText("");
        txfldType_id.setText("");
        txfldTypeofpackage.setText("");
        txfldKilogram.setText("");
        txfldPrice.setText("");
        txfldDelivery_id.setText("");
        txfldDelivery.setText("");
        txfldpayment_id.setText("");
        txfldPayment.setText("");
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void txfldBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfldBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfldBrandActionPerformed

    private void txfldType_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfldType_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfldType_idActionPerformed

    private void txfldpayment_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfldpayment_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfldpayment_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DogeCRUDScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DogeCRUDScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DogeCRUDScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DogeCRUDScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DogeCRUDScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDisplayRecords;
    private javax.swing.JTextField txfldBrand;
    private javax.swing.JTextField txfldDelivery;
    private javax.swing.JTextField txfldDelivery_id;
    private javax.swing.JTextField txfldFirstname;
    private javax.swing.JTextField txfldFlavor;
    private javax.swing.JTextField txfldId;
    private javax.swing.JTextField txfldKilogram;
    private javax.swing.JTextField txfldLastname;
    private javax.swing.JTextField txfldMobile;
    private javax.swing.JTextField txfldPayment;
    private javax.swing.JTextField txfldPrice;
    private javax.swing.JTextField txfldType_id;
    private javax.swing.JTextField txfldTypeofpackage;
    private javax.swing.JTextField txflddogfood_id;
    private javax.swing.JTextField txfldpayment_id;
    // End of variables declaration//GEN-END:variables
}
