/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jurado_project;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Vladimir Ken P. Jurado
 * version 1.0
 * Date: 3/27/2022
 */
public class DogeMainScreen extends javax.swing.JFrame {

    /**
     * Creates new form DogeMainScreen
     */
    
    //initialize DBHelper
    DBHelper1 dbh = new DBHelper1();
            
    public DogeMainScreen() {
        initComponents();
        //calls connectDB method so when the program starts , it's already connected to the database
        try{
            dbh.connectDB();
        } catch (Exception ex) {
            Logger.getLogger(DogeMainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txfldCostumer = new javax.swing.JTextField();
        lblBrand = new javax.swing.JLabel();
        lblFlavor = new javax.swing.JLabel();
        txfldBrand = new javax.swing.JTextField();
        txfldFlavor = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txfldDogfood = new javax.swing.JLabel();
        txfldDogfood_id = new javax.swing.JTextField();
        cbBrand = new javax.swing.JComboBox<>();
        cbFlavor = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 245, 220));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(148, 107, 69));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Doge Dog Food Information System");

        lblName.setText("Customer ID");
        lblName.setName("lblName"); // NOI18N

        txfldCostumer.setName("txfldCostumer"); // NOI18N
        txfldCostumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfldCostumerActionPerformed(evt);
            }
        });

        lblBrand.setText("Brand");
        lblBrand.setName("lblBrand"); // NOI18N

        lblFlavor.setText("Flavor");
        lblFlavor.setName("lblFlavor"); // NOI18N

        txfldBrand.setName("txfldBrand"); // NOI18N
        txfldBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfldBrandActionPerformed(evt);
            }
        });

        txfldFlavor.setName("txfldFlavor"); // NOI18N

        btnSubmit.setBackground(new java.awt.Color(255, 153, 0));
        btnSubmit.setText("Next");
        btnSubmit.setName("btnSubmit"); // NOI18N
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 153, 0));
        btnClear.setText("Clear");
        btnClear.setName("btnSubmit"); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        txfldDogfood.setText("Dogfood ID");
        txfldDogfood.setName("txfldDogfood"); // NOI18N

        txfldDogfood_id.setName("txfldDogfood_id"); // NOI18N
        txfldDogfood_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfldDogfood_idActionPerformed(evt);
            }
        });

        cbBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Pedigree", "Alpo", "Iams" }));
        cbBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBrandActionPerformed(evt);
            }
        });

        cbFlavor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Puppy Chicken", "Beef Flavor", "Adult", " ", "Beef Liver and Vegetable", "Prime cuts", "T-Bonz BBQ", " ", "Mother and Baby", "Adult Dog", "Small Breed", " ", " " }));
        cbFlavor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFlavorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                                .addComponent(txfldCostumer, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txfldDogfood)
                                        .addGap(178, 178, 178))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblBrand)
                                            .addComponent(lblFlavor))
                                        .addGap(91, 91, 91)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbFlavor, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbBrand, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(91, 91, 91)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txfldFlavor, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(txfldBrand, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txfldDogfood_id)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txfldCostumer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfldDogfood)
                    .addComponent(txfldDogfood_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfldBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBrand)
                    .addComponent(cbBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfldFlavor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFlavor)
                    .addComponent(cbFlavor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnClear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfldDogfood_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfldDogfood_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfldDogfood_idActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txfldCostumer.setText("");
        txfldDogfood_id.setText("");
        txfldBrand.setText("");
        txfldFlavor.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:           
        int cust_id = Integer.parseInt(txfldCostumer.getText());
        int dogfood_id = Integer.parseInt(txfldDogfood_id.getText());
        String brand = txfldBrand.getText();
        String flavor = txfldFlavor.getText();

        boolean ins = dbh.insertRecord(cust_id, dogfood_id, brand, flavor);
        if (ins)
            System.out.println("Good. heading to next, Arf arf!");
        else
            JOptionPane.showMessageDialog(null, "Arf arf! There's somethings missing");
        
        new DogeTypeDogFood().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txfldBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfldBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfldBrandActionPerformed

    private void txfldCostumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfldCostumerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txfldCostumerActionPerformed

    private void cbBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBrandActionPerformed
        // TODO add your handling code here:
        String brand = cbBrand.getSelectedItem().toString();
        txfldBrand.setText(brand);
    }//GEN-LAST:event_cbBrandActionPerformed

    private void cbFlavorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFlavorActionPerformed
        // TODO add your handling code here:
        String flavor = cbFlavor.getSelectedItem().toString();
        txfldFlavor.setText(flavor);
    }//GEN-LAST:event_cbFlavorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DogeMainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbBrand;
    private javax.swing.JComboBox<String> cbFlavor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblFlavor;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextField txfldBrand;
    private javax.swing.JTextField txfldCostumer;
    private javax.swing.JLabel txfldDogfood;
    private javax.swing.JTextField txfldDogfood_id;
    private javax.swing.JTextField txfldFlavor;
    // End of variables declaration//GEN-END:variables
}
